[2025-08-28T18:42:14.160+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-08-28T18:42:14.226+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fraud_detection_training.cleanup_resources scheduled__2025-08-27T03:00:00+00:00 [queued]>
[2025-08-28T18:42:14.246+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fraud_detection_training.cleanup_resources scheduled__2025-08-27T03:00:00+00:00 [queued]>
[2025-08-28T18:42:14.247+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-08-28T18:42:14.266+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): cleanup_resources> on 2025-08-27 03:00:00+00:00
[2025-08-28T18:42:14.272+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=187) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-28T18:42:14.276+0000] {standard_task_runner.py:72} INFO - Started process 188 to run task
[2025-08-28T18:42:14.277+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fraud_detection_training', 'cleanup_resources', 'scheduled__2025-08-27T03:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/fraud_detection_training_dag.py', '--cfg-path', '/tmp/tmp5ii2oge5']
[2025-08-28T18:42:14.278+0000] {standard_task_runner.py:105} INFO - Job 11: Subtask cleanup_resources
[2025-08-28T18:42:14.331+0000] {task_command.py:467} INFO - Running <TaskInstance: fraud_detection_training.cleanup_resources scheduled__2025-08-27T03:00:00+00:00 [running]> on host fbfd4480322c
[2025-08-28T18:42:14.432+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='datamasterylab.com' AIRFLOW_CTX_DAG_ID='fraud_detection_training' AIRFLOW_CTX_TASK_ID='cleanup_resources' AIRFLOW_CTX_EXECUTION_DATE='2025-08-27T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-27T03:00:00+00:00'
[2025-08-28T18:42:14.437+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-08-28T18:42:14.460+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-08-28T18:42:14.461+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'rm -f /app/tmp/*.pkl']
[2025-08-28T18:42:14.474+0000] {subprocess.py:99} INFO - Output:
[2025-08-28T18:42:14.486+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-08-28T18:42:14.514+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-08-28T18:42:14.515+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=fraud_detection_training, task_id=cleanup_resources, run_id=scheduled__2025-08-27T03:00:00+00:00, execution_date=20250827T030000, start_date=20250828T184214, end_date=20250828T184214
[2025-08-28T18:42:14.548+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-08-28T18:42:14.560+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-28T18:42:14.563+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-08-28T18:59:16.150+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-08-28T18:59:16.159+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fraud_detection_training.cleanup_resources scheduled__2025-08-27T03:00:00+00:00 [queued]>
[2025-08-28T18:59:16.162+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fraud_detection_training.cleanup_resources scheduled__2025-08-27T03:00:00+00:00 [queued]>
[2025-08-28T18:59:16.163+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-08-28T18:59:16.167+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): cleanup_resources> on 2025-08-27 03:00:00+00:00
[2025-08-28T18:59:16.171+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=172) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-28T18:59:16.172+0000] {standard_task_runner.py:72} INFO - Started process 173 to run task
[2025-08-28T18:59:16.172+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fraud_detection_training', 'cleanup_resources', 'scheduled__2025-08-27T03:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/fraud_detection_training_dag.py', '--cfg-path', '/tmp/tmpm87hwz2n']
[2025-08-28T18:59:16.172+0000] {standard_task_runner.py:105} INFO - Job 16: Subtask cleanup_resources
[2025-08-28T18:59:16.192+0000] {task_command.py:467} INFO - Running <TaskInstance: fraud_detection_training.cleanup_resources scheduled__2025-08-27T03:00:00+00:00 [running]> on host d31ca6a4308c
[2025-08-28T18:59:16.221+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='nguyentientai223.com' AIRFLOW_CTX_DAG_ID='fraud_detection_training' AIRFLOW_CTX_TASK_ID='cleanup_resources' AIRFLOW_CTX_EXECUTION_DATE='2025-08-27T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-27T03:00:00+00:00'
[2025-08-28T18:59:16.222+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-08-28T18:59:16.230+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-08-28T18:59:16.231+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'rm -f /app/tmp/*.pkl']
[2025-08-28T18:59:16.236+0000] {subprocess.py:99} INFO - Output:
[2025-08-28T18:59:16.242+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-08-28T18:59:16.260+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-08-28T18:59:16.260+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=fraud_detection_training, task_id=cleanup_resources, run_id=scheduled__2025-08-27T03:00:00+00:00, execution_date=20250827T030000, start_date=20250828T185916, end_date=20250828T185916
[2025-08-28T18:59:16.312+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-08-28T18:59:16.319+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-28T18:59:16.320+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
